unicode-locale-id =  unicode-language-id
                     [unicode-locale-extensions]

unicode-locale-extensions = sep "u" 
                          (1*(sep keyword)
                         / 1*(sep attribute) *(sep keyword))

keyword = key [sep type]

key = 2alphanum

type = 3*8alphanum

attribute = 3*8alphanum

alphanum = ALPHA / DIGIT
