%%% User Extentions for Erlang 
%%%
%%% @package  ux_unidata
%%% @author   Uvarov Michael <freeakk@gmail.com>
%%% @license  http://www.fsf.org/copyleft/lgpl.html LGPL
%%%
%%% @copyright 2010 Uvarov Michael.
%%% %CopyrightBegin%
%%%  Copyright 2010 Uvarov Michael  
%%%
%%%  See the enclosed file COPYING for license information (LGPL). If you
%%%  did not receive this file, see http://www.fsf.org/copyleft/lgpl.html
%%% %CopyrightEnd%

-define(UNIDATA_VERSION,   "UNIDATA").
-define(UCADATA_VERSION,   "UCA").

%% Path to UNIDATA
-define(UNIDATA_DIRECTORY, "../priv/" ++ ?UNIDATA_VERSION ++ "/").
-define(UCADATA_DIRECTORY, "../priv/" ++ ?UCADATA_VERSION ++ "/").
-define(COLLATION_TEST_DATA_DIRECTORY, ?UCADATA_DIRECTORY ++ "CollationTest/").

%% Autogenerated *.hrl files
-define(UX_STRING_INC,     "../src/unidata/"). % from ebin/
