
-define(UNIDATA_VERSION,   "UNIDATA").
-define(UCADATA_VERSION,   "UCA").

%% Path to UNIDATA
-define(UNIDATA_DIRECTORY, "../priv/" ++ ?UNIDATA_VERSION ++ "/").
-define(UCADATA_DIRECTORY, "../priv/" ++ ?UCADATA_VERSION ++ "/").
-define(COLLATION_TEST_DATA_DIRECTORY, ?UCADATA_DIRECTORY ++ "CollationTest/").

%% Autogenerated *.hrl files
-define(UX_STRING_INC,     "../src/string/").
