
-define(UNIDATA_VERSION,   "UNIDATA").
-define(UCADATA_VERSION,   "UCA").

%% Path to UNIDATA
-define(UNIDATA_DIRECTORY, "../priv/" ++ ?UNIDATA_VERSION ++ "/").
-define(UCADATA_DIRECTORY, "../priv/" ++ ?UCADATA_VERSION ++ "/").
-define(COLLATION_TEST_DATA_DIRECTORY, ?UCADATA_DIRECTORY ++ "CollationTest/").

%% Autogenerated *.hrl files
-define(UX_STRING_INC,     "../src/string/").

% Records
-record(unistr_info, {
        str,            % Input string
        comment,        % Array of char's comments
        nfd,            % Normal Form D
        nfc,            % Normal Form C
        ducet,          % Weight's from ducet for each symbol
        ccc,            % Canonical Combining Classes 
        col_sort_array_non_ignorable, % Collation sort array
        col_sort_array_blanked, % Collation sort array
        col_sort_array_shifted, % Collation sort array
        col_sort_array_shift_trimmed, % Collation sort array
        blocks          % Blocks from Unicode Character Database
        }).
