
-define(UNIDATA_VERSION,   "UNIDATA").

%% Path to UNIDATA
-define(UNIDATA_DIRECTORY, "../priv/" ++ ?UNIDATA_VERSION ++ "/").

%% Autogenerated *.hrl files
-define(UX_STRING_INC,     "../src/string/").

